#!/usr/bin/env python3
"""Generate the 64-entry EXP/EXP2 table for unsigned centered interpolation.

No SFUConfig widths change. Coefficients represent c0/2^25, bias+c1/2^17,
c2/2^13; c0/c1/c2 fit 26/16/12 bits. Bias is 1/2 for segments 0..33,
otherwise 1, decoded in hardware using c0 < 48408813. Evaluate the truncating
integer datapath, including ceil on the subtracted linear term.
Requires numpy. Search is deterministic, and every selected segment is
validated against a double reference on all 131072 Q23 local arguments.
This is not a proof for EXP's
additional range reduction, nor an exhaustive test of all FP32 inputs.
"""
import argparse
import math
from pathlib import Path
import numpy as np

WIDTHS = (26, 16, 12)
LOCAL_SIZE = 1 << 17
CENTER = 1 << 16


def geometry(r):
    m = np.abs(r - CENTER)
    return m, (m * m) >> 18, r < CENTER


def terms(c1, c2, geometry, bias):
    m, square, left = geometry
    product = c1 * m + (m << (16 if bias == 0.5 else 17))
    linear = product >> 15
    # ceil on left preserves floor(-product / 32768) using unsigned products.
    linear = np.where(left, -(linear + ((product & 32767) != 0)), linear)
    return linear + ((c2 * square) >> 16)


def score(c0, rest, ref):
    actual = (c0 + rest) >> 2
    error = actual - ref
    return float(np.max(np.abs(error))), float(np.mean(np.abs(error)))


def generate_segment(segment, previous):
    # Quadratic interpolation at three Chebyshev nodes gives a useful seed.
    center = (segment + 0.5) / 64.0
    node = math.sqrt(3.0) / 256.0
    f0 = 2.0**center
    a = math.log(2.0) * node
    bias = 0.5 if segment < 34 else 1.0
    seed1 = round((f0 * math.sinh(a) / node - bias) * 2**17)
    seed2 = round(f0 * 2.0 * math.sinh(a / 2.0)**2 / node**2 * 2**13)

    r = np.unique(np.concatenate((np.arange(0, LOCAL_SIZE, 32),
        [0, 1, CENTER-1, CENTER, CENTER+1, LOCAL_SIZE-2, LOCAL_SIZE-1])))
    geom = geometry(r)
    ref = np.exp2(segment / 64.0 + r / 2**23) * 2**23
    candidates = []
    for c1 in range(max(0, seed1-2), min(1 << 16, seed1+3)):
        for c2 in range(max(0, seed2-24), min(1 << 12, seed2+25)):
            rest = terms(c1, c2, geom, bias)
            # Center the real residual and compensate the final >>2 bias.
            residual = ref * 4 - rest
            base = round((float(residual.min()) + float(residual.max())) / 2 + 1.5)
            for c0 in range(base-2, base+3):
                if 0 <= c0 < (1 << 26) and (c0 < 48408813) == (bias == 0.5):
                    candidates.append((score(c0, rest, ref), (c0,c1,c2)))
    candidates.sort()

    full_r = np.arange(LOCAL_SIZE, dtype=np.int64)
    full_geom = geometry(full_r)
    full_ref = np.exp2(segment / 64.0 + full_r / 2**23) * 2**23
    best = None
    for _, coeffs in candidates[:128]:
        c0,c1,c2 = coeffs
        rest = terms(c1,c2,full_geom,bias)
        actual = (c0 + rest) >> 2
        if actual[0] < previous or actual[-1] >= (1 << 24):
            continue
        if segment == 0 and actual[0] != (1 << 23):
            continue
        key = (score(c0,rest,full_ref), coeffs)
        if best is None or key < best:
            best = key
    if best is None:
        raise RuntimeError(f"no boundary-compatible coefficients for segment {segment}")
    (max_err, avg_err), coeffs = best
    actual = (coeffs[0] + terms(coeffs[1], coeffs[2], full_geom,bias)) >> 2
    # Both the Q23 kernel and transitions between table entries must be monotone.
    if np.any(actual[1:] < actual[:-1]):
        raise RuntimeError(f"segment {segment} is not monotone")
    return coeffs, max_err, avg_err, int(actual[0]), int(actual[-1])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output',type=Path,default=Path(__file__).resolve().parents[1]/'lut/exp2-coeffs.txt')
    parser.add_argument('--check',action='store_true',help='compare generated bytes to existing table')
    args=parser.parse_args()
    rows=[]; maximum=0.; avg=0.; previous=1 << 23
    for segment in range(64):
        coeffs, error, mean, first, last=generate_segment(segment, previous)
        if first < previous:
            raise RuntimeError(f"nonmonotone table boundary {segment}")
        previous=last; maximum=max(maximum,error); avg+=mean/64
        assert all(0<=c<(1<<w) for c,w in zip(coeffs,WIDTHS))
        rows.append(' '.join(f'{c:X}' for c in coeffs)+'\n')
    content=''.join(rows)
    if args.check:
        if args.output.read_text()!=content:
            raise SystemExit('table does not match deterministic generation')
    else:
        args.output.write_text(content)
    print(f'64 x 54-bit table: max real-value kernel error {maximum:.9f} ULP; mean {avg:.9f} ULP')
    print('Exhaustive Q23 kernel points: 8388608; monotonicity PASS')

if __name__=='__main__':
    main()
